apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: probeserver
  namespace: default
  labels:
    zone: default
    app: probeserver
    deployment: probe
    version: "1.0"
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: probeserver
  replicas: 1
  template:
    metadata:
      labels:
        zone: default
        app: probeserver
        deployment: probe
        version: "1.0"
        prometheus.io/scrape: 'true'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        controller.kubernetes.io/pod-deletion-cost: '1000'
    spec:
      
      terminationGracePeriodSeconds : 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - tb-cloud-vm-8-1
      schedulerName: default-scheduler
      containers:
        - name: probeserver
          image: paprikaw/mubench:dev
          imagePullPolicy: Always
          ports:
            - name: http-mubpodport
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: microservice-workmodel
              mountPath: /app/MSConfig
            - name: microservice-internal-services
              mountPath: /app/MSConfig/InternalServiceFunctions
          env:
            - name: APP
              value: probeserver
            - name: EXECUTION_TIME_MAP
              valueFrom:
                configMapKeyRef:
                  name: execution-time-config
                  key: json_data
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PN
              value: '1'
            - name: TN
              value: '1'
            - name: CLOUD_LATENCY
              value: '0.05'
            - name: CLOUD_NODE_NAME_PREFIX
              value: 'tb-cloud'
          resources: 
            limits:
              cpu: 100m
              memory: 100Mi    
        
      

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: microservice-workmodel
          configMap:
            name: workmodel
        - name: microservice-internal-services
          configMap:
            name: internal-services        
---
apiVersion: v1
kind: Service
metadata:
  name: probeserver
  namespace: default
  labels:
    app: probeserver
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: http-mubserviceport
  - port: 51313
    targetPort: 51313
    name: grpc-mubserviceport
  selector:
    app: probeserver
