apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: detection
  namespace: default
  labels:
    zone: default
    app: detection
    deployment: mubench
    version: "1.0"
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: detection
  replicas: 3
  template:
    metadata:
      labels:
        zone: default
        app: detection
        deployment: mubench
        version: "1.0"
        prometheus.io/scrape: 'true'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        controller.kubernetes.io/pod-deletion-cost: '1000'
    spec:
      
      terminationGracePeriodSeconds : 3
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - tb-cloud-vm-8-1
                - tb-cloud-vm-8-2
                - tb-edge-vm-4-1
                - tb-edge-vm-4-2
                - tb-edge-vm-2-1
                - tb-edge-vm-2-2
            weight: 1
      schedulerName: default-scheduler
      containers:
        - name: detection
          image: paprikaw/mubench:dev
          ports:
            - name: http-mubpodport
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: microservice-workmodel
              mountPath: /app/MSConfig
            - name: microservice-internal-services
              mountPath: /app/MSConfig/InternalServiceFunctions
          env:
            - name: APP
              value: detection
            - name: EXECUTION_TIME_MAP
              valueFrom:
                configMapKeyRef:
                  name: execution-time-config
                  key: json_data
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PN
              value: '4'
            - name: TN
              value: '16'
            - name: CLOUD_LATENCY
              value: '0.05'
            - name: CLOUD_NODE_NAME_PREFIX
              value: 'tb-cloud'
          resources: 
            requests:
              cpu: 900m
              memory: 900Mi
            limits:
              cpu: 900m
              memory: 900Mi    
        
      

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: microservice-workmodel
          configMap:
            name: workmodel
        - name: microservice-internal-services
          configMap:
            name: internal-services        
---
apiVersion: v1
kind: Service
metadata:
  name: detection
  namespace: default
  labels:
    app: detection
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: http-mubserviceport
  - port: 51313
    targetPort: 51313
    name: grpc-mubserviceport
  selector:
    app: detection
