apiVersion: v1
data:
  workmodel.json: |
    {
      "client": {
        "external_services": [
          {
            "seq_len": 1,
            "services": [
              "aggregator"
            ]
          }
        ],
        "internal_service": {
          "loader": {
            "cpu_stress": {
              "run": false,
              "range_complexity": [
                3,
                3
              ],
              "thread_pool_size": 1,
              "trials": 1
            },
            "memory_stress": {
              "run": false,
              "memory_size": 100,
              "memory_io": 100
            },
            "disk_stress": {
              "run": false,
              "tmp_file_name": "mubtestfile.txt",
              "disk_write_block_count": 10,
              "disk_write_block_size": 1024
            },
            "sleep_stress": {
              "run": false,
              "sleep_time": 0.01
            },
            "mean_bandwidth": 1
          }
        },
        "request_method": "rest",
        "workers": 4,
        "threads": 16,
        "replicas": 1,
        "cpu-requests": "600m",
        "cpu-limits": "600m",
        "memory-requests": "600Mi",
        "memory-limits": "600Mi",
        "is_client": true,
        "affinity_required": true,
        "node_affinity": [
          "tb-client-vm-2-1"
        ],
        "url": "client.default.svc.cluster.local",
        "path": "/api/v1",
        "image": "paprikaw/mubench:dev",
        "namespace": "default"
      },
      "aggregator": {
        "external_services": [
          {
            "seq_len": 1,
            "services": [
              "detection"
            ]
          },
          {
            "seq_len": 1,
            "services": [
              "machine-learning"
            ]
          }
        ],
        "internal_service": {
          "loader": {
            "cpu_stress": {
              "run": true,
              "range_complexity": [
                200,
                200
              ],
              "thread_pool_size": 1,
              "trials": 2
            },
            "memory_stress": {
              "run": true,
              "memory_size": 1000,
              "memory_io": 1000
            },
            "disk_stress": {
              "run": false,
              "tmp_file_name": "mubtestfile.txt",
              "disk_write_block_count": 10,
              "disk_write_block_size": 1024
            },
            "sleep_stress": {
              "run": false,
              "sleep_time": 0.01
            },
            "mean_bandwidth": 10
          }
        },
        "request_method": "rest",
        "workers": 4,
        "threads": 16,
        "replicas": 3,
        "cpu-requests": "600m",
        "cpu-limits": "600m",
        "memory-requests": "600Mi",
        "memory-limits": "600Mi",
        "node_affinity": [
          "tb-cloud-vm-8-1",
          "tb-cloud-vm-8-2",
          "tb-edge-vm-4-1",
          "tb-edge-vm-4-2",
          "tb-edge-vm-2-1",
          "tb-edge-vm-2-2"
        ],
        "url": "aggregator.default.svc.cluster.local",
        "path": "/api/v1",
        "image": "paprikaw/mubench:dev",
        "namespace": "default"
      },
      "detection": {
        "external_services": [
          {
            "seq_len": 1,
            "services": []
          }
        ],
        "internal_service": {
          "loader": {
            "cpu_stress": {
              "run": true,
              "range_complexity": [
                200,
                200
              ],
              "thread_pool_size": 1,
              "trials": 4
            },
            "memory_stress": {
              "run": true,
              "memory_size": 1000,
              "memory_io": 1000
            },
            "disk_stress": {
              "run": false,
              "tmp_file_name": "mubtestfile.txt",
              "disk_write_block_count": 1000,
              "disk_write_block_size": 1024
            },
            "sleep_stress": {
              "run": false,
              "sleep_time": 0.01
            },
            "mean_bandwidth": 10
          }
        },
        "request_method": "rest",
        "workers": 4,
        "threads": 16,
        "memory-requests": "900Mi",
        "memory-limits": "900Mi",
        "cpu-requests": "900m",
        "cpu-limits": "900m",
        "replicas": 3,
        "node_affinity": [
          "tb-cloud-vm-8-1",
          "tb-cloud-vm-8-2",
          "tb-edge-vm-4-1",
          "tb-edge-vm-4-2",
          "tb-edge-vm-2-1",
          "tb-edge-vm-2-2"
        ],
        "url": "detection.default.svc.cluster.local",
        "path": "/api/v1",
        "image": "paprikaw/mubench:dev",
        "namespace": "default"
      },
      "machine-learning": {
        "external_services": [
          {
            "seq_len": 1,
            "services": [
              "db"
            ]
          }
        ],
        "internal_service": {
          "loader": {
            "cpu_stress": {
              "run": true,
              "range_complexity": [
                400,
                400
              ],
              "thread_pool_size": 1,
              "trials": 8
            },
            "memory_stress": {
              "run": true,
              "memory_size": 2000,
              "memory_io": 2000
            },
            "disk_stress": {
              "run": false,
              "tmp_file_name": "mubtestfile.txt",
              "disk_write_block_count": 100,
              "disk_write_block_size": 1024
            },
            "sleep_stress": {
              "run": false,
              "sleep_time": 0.01
            },
            "mean_bandwidth": 10
          }
        },
        "request_method": "rest",
        "workers": 4,
        "threads": 16,
        "memory-requests": "1400Mi",
        "memory-limits": "1400Mi",
        "cpu-requests": "1400m",
        "cpu-limits": "1400m",
        "replicas": 3,
        "node_affinity": [
          "tb-cloud-vm-8-1",
          "tb-cloud-vm-8-2",
          "tb-edge-vm-4-1",
          "tb-edge-vm-4-2",
          "tb-edge-vm-2-1",
          "tb-edge-vm-2-2"
        ],
        "url": "machine-learning.default.svc.cluster.local",
        "path": "/api/v1",
        "image": "paprikaw/mubench:dev",
        "namespace": "default"
      },
      "db": {
        "external_services": [],
        "internal_service": {
          "loader": {
            "cpu_stress": {
              "run": true,
              "range_complexity": [
                100,
                100
              ],
              "thread_pool_size": 1,
              "trials": 1
            },
            "memory_stress": {
              "run": true,
              "memory_size": 100,
              "memory_io": 100
            },
            "disk_stress": {
              "run": false,
              "tmp_file_name": "mubtestfile.txt",
              "disk_write_block_count": 10,
              "disk_write_block_size": 1024
            },
            "sleep_stress": {
              "run": false,
              "sleep_time": 0.01
            },
            "mean_bandwidth": 10
          }
        },
        "request_method": "rest",
        "workers": 4,
        "threads": 16,
        "replicas": 3,
        "cpu-requests": "400m",
        "cpu-limits": "400m",
        "memory-requests": "400Mi",
        "memory-limits": "400Mi",
        "node_affinity": [
          "tb-cloud-vm-8-1",
          "tb-cloud-vm-8-2",
          "tb-edge-vm-4-1",
          "tb-edge-vm-4-2",
          "tb-edge-vm-2-1",
          "tb-edge-vm-2-2"
        ],
        "url": "db.default.svc.cluster.local",
        "path": "/api/v1",
        "image": "paprikaw/mubench:dev",
        "namespace": "default"
      }
    }
kind: ConfigMap
metadata:
  name: workmodel
  namespace: default
